import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {
  const[addressList, addAddress]= useState([])
  const registerUser = event => {
    let addresses = []
    addresses.push(event.target.name.value)
    addAddress(addressList.concat(addresses))
    event.preventDefault()
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form onSubmit={registerUser}>
          <label htmlFor="name">NFT Contract Address</label>
          <input id="name" type="text" autoComplete="name" required />
          <button type="submit">Add</button>
        </form>
        {addressList.map((e, i)=>{
          return(
            <div key={i}>{e}</div>
          )
        })}
      </main>
      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
